const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const crypto=require('node:crypto');
function canonical(v){return Array.isArray(v)?'['+v.map(canonical).join(',')+']':v&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}':JSON.stringify(v);}
function payload(dir){const f=path.join(dir,'fake.mp4');fs.writeFileSync(f,'test-only-not-a-video');const p={version:1,job_id:'fixture',mode:'publish',title:'test',description:'',tags:['test'],privacy:'private',publish_at:null,made_for_kids:false,contains_synthetic_media:false,notify_subscribers:false,assets:{video:{path:f,size:fs.statSync(f).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex')}}};p.fingerprint=crypto.createHash('sha256').update(canonical(p)).digest('hex');return p;}
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'youtube-control-test-'));t.after(()=>fs.rmSync(root,{recursive:true}));return root;}
const options={decision:'publish',commit:true,channelId:'UC'+'a'.repeat(22)};
test('no commit never touches browser or claim',async t=>{const m=await import('./youtube_browser.mjs');let calls=0;await assert.rejects(m.execute({session:()=>calls++},payload(fixture(t)),{...options,commit:false},{claim:()=>calls++}),e=>e.status==='NEEDS_AUTHORIZATION');assert.equal(calls,0);});
test('decision mismatch never touches browser',async t=>{const m=await import('./youtube_browser.mjs');await assert.rejects(m.execute({},payload(fixture(t)),{...options,decision:'schedule'},{}),e=>e.status==='DECISION_MODE_MISMATCH');});
test('kids content with notifications stops before browser or claim',async t=>{const m=await import('./youtube_browser.mjs');const p=payload(fixture(t));p.made_for_kids=true;p.notify_subscribers=true;delete p.fingerprint;p.fingerprint=crypto.createHash('sha256').update(canonical(p)).digest('hex');let calls=0;await assert.rejects(m.execute({session:async()=>calls++},p,options,{claim:()=>calls++}),e=>e.status==='DECLARATION_CONFLICT');assert.equal(calls,0);});
test('channel mismatch stops before upload',async t=>{const m=await import('./youtube_browser.mjs');let uploads=0;await assert.rejects(m.execute({session:async()=>{throw new m.Stop('CHANNEL_MISMATCH','wrong channel')},upload:()=>uploads++},payload(fixture(t)),options,{}));assert.equal(uploads,0);});
test('changed prepared file cannot upload',async t=>{const m=await import('./youtube_browser.mjs');const p=payload(fixture(t));fs.appendFileSync(p.assets.video.path,'changed');await assert.rejects(m.execute({},p,options,{}),e=>e.status==='SOURCE_CHANGED');});
test('one upload and one submit only; receipt remains pending',async t=>{const m=await import('./youtube_browser.mjs');const root=fixture(t);const calls=[];const driver={session:async()=>{},videoId:'abcdefghijk',upload:async()=>calls.push('upload'),metadata:async()=>calls.push('metadata'),advanceToVisibility:async()=>{},visibility:async()=>{},submit:async()=>{calls.push('submit');return {status:'SUBMITTED',outcome:'pending'}}};const p=payload(root);const result=await m.execute(driver,p,options,m.journalAt(root));assert.equal(result.outcome,'pending');await assert.rejects(m.execute(driver,p,options,m.journalAt(root)),e=>e.status==='JOB_ALREADY_ATTEMPTED');assert.deepEqual(calls,['upload','metadata','submit']);});
test('failure after upload stays partial and is never replayed',async t=>{const m=await import('./youtube_browser.mjs');const root=fixture(t);let uploads=0;const p=payload(root);const driver={session:async()=>{},upload:async()=>uploads++,metadata:async()=>{throw new m.Stop('ADAPTER_OUTDATED','missing field')}};const result=await m.execute(driver,p,options,m.journalAt(root));assert.equal(result.outcome,'partial');await assert.rejects(m.execute(driver,p,options,m.journalAt(root)));assert.equal(uploads,1);});
test('schedule converts the instant to UTC and rejects elapsed times',async()=>{const m=await import('./youtube_browser.mjs');const year=new Date().getUTCFullYear()+1;const s=m.utcSchedule(`${year}-09-05T18:34:00-07:00`);assert.equal(s.date,`${year}-09-06`);assert.equal(s.time,'01:34');assert.throws(()=>m.utcSchedule('2000-01-01T00:00:00Z'),e=>e.status==='SCHEDULE_EXPIRED');});
test('thumbnail uses the unique image file input without relying on translated button text',async()=>{const m=await import('./youtube_browser.mjs');const calls=[];const input={count:async()=>1,setInputFiles:async file=>calls.push(file)};const page={locator:selector=>{assert.equal(selector,'ytcp-uploads-dialog input[type=file][accept*="image"]');return input;}};const driver=new m.StudioDriver(page,options.channelId);await driver.uploadThumbnail('/tmp/cover.jpg');assert.deepEqual(calls,['/tmp/cover.jpg']);});
